name: CI
on: [push, pull_request]
jobs:
  build:
    name: MSBuild
    # runs-on: self-hosted
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Setup MSBuild.exe
      uses: microsoft/Setup-MSBuild@v1.0.2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: csharp

    - name: MSBuild
      run: msbuild -restore:true TeamMate.csproj
      working-directory: ./Source/TeamMate
      shell: cmd

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
